# Generated by Django 3.2.6 on 2021-08-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de la respuesta'),
        ),
    ]
