# Generated by Django 3.2.6 on 2021-08-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20210816_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizusuario',
            old_name='puntaje',
            new_name='puntaje_total',
        ),
    ]
