# Generated by Django 3.2.6 on 2021-08-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_rename_puntaje_quizusuario_puntaje_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='puntaje total'),
        ),
    ]
